## 121. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/121.html'>потенциалис</a><div class='box'><iframe src='https://agricolamz.github.io/The_Circassian_Isoglosses_Database/121.html' width = '400px' height = '300px'></iframe></div>mood
### Description

Потенциалис выражается разными суффиксами.

### Values
There are the following value for each idiom:

* Bzhedug  -ŝ (но -f с глаголом ṣ̂e- "делать") [Керашева 1957: 267] (вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапсугском и бжедугском, получается, у глагола "делать" потенциалис кабардинский)
* Kabardian  -f [Керашева 1957: 267] (вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапсугском и бжедугском, получается, у глагола "делать" потенциалис кабардинский)
* Shapsug  -ŝ (но -f с глаголом ṣ̂e- "делать") [Керашева 1957: 267] (вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапсугском и бжедугском, получается, у глагола "делать" потенциалис кабардинский)
* SWC  -ŝ [Керашева 1957: 267] (вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапсугском и бжедугском, получается, у глагола "делать" потенциалис кабардинский)

