## 122. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/122.html'>преверб č̣’e-λə-rə "возле"</a>
preverb; spatial; morphology
### Description

В темиргоевском преверб č̣’e-λə- "возле" может употребляться без λə-. Кроме того, в темиргоевском может употребляться в этом значении преверб bʁʷode (который "более характерен для кабардино-черкесского")

### Values
There are the following value for each idiom:

* Bzhedug  č̣’e-λə-rə [Ситимова 2004: 102-103] (На самом деле, в словоформах, приведены в пример, есть ещё преверб rə-: č̣’e-(λə-)rə-s "сидит возле кого-чего-л." и в следующем же абзаце написано про преверб č̣’e-λə-rə- (примеры с похожим значением).)
* Temirgoi  č̣’e-λə-rə, č̣’e-rə, bʁʷode [Ситимова 2004: 102-103] (На самом деле, в словоформах, приведены в пример, есть ещё преверб rə-: č̣’e-(λə-)rə-s "сидит возле кого-чего-л." и в следующем же абзаце написано про преверб č̣’e-λə-rə- (примеры с похожим значением).)
* Kabardian  bʁʷode [Ситимова 2004: 102] (На самом деле, в словоформах, приведены в пример, есть ещё преверб rə-: č̣’e-(λə-)rə-s "сидит возле кого-чего-л." и в следующем же абзаце написано про преверб č̣’e-λə-rə- (примеры с похожим значением).)
* Bzhedug  č̣’e-λə-rə [Тхаркахо 1993: 77] 
* Temirgoi  č̣’e-rə [Тхаркахо 1993: 77] 

