## 148. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/148.html'>прошедшее -aa вместо -ʁe</a>
### Description



### Values
There are the following value for each idiom:

* Bzhedug  в формах прошедшего; второй из двух показателей -ʁe в формах давнопрошедшего; может быть перед кондиционалисом -me; в основном в непереходных глаголах; перед усилительным -jə [Ситимова 2004: 89-90; 91-92] (Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).)
* Temirgoi  может быть перед кондиционалисом -me; в сочетании -FUT-PST-PST первый из показателей; в основном в непереходных глаголах [Ситимова 2004: 89-90; 91-92] (Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).)
* Abzakh  нет [Ситимова 2004: 91] (Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).)
* Shapsug  нет [Ситимова 2004: 91] (Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).)

