## 162. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/162.html'>устранение зияния между /e/ и -e- DYN</a><div class='box'><iframe src='https://agricolamz.github.io/The_Circassian_Isoglosses_Database/162.html' width = '400px' height = '300px'></iframe></div>morphonology
### Description

Можно предполагать, что в случаях, когда показателю динамичности -e- предшествует другая гласная /e/, в бжедугском удаляется гласная показателя динамичности, а в темиргоевском удаляется предшествующая гласная. Это проявляется в словформах, где после показателя динамичности в составе основы есть только односложный корень с гласной /e/: в бжедугском в таком случае происходит чередования /e/~/a/, а в темиргоевском — нет. См. в [Ситимова 2004: 96] темиргоевские формы wə-s-e-že [2sg.io-1sg.abs-obl+dyn-ждать] "я тебя жду", ŝʷə-t-e-že [2pl.io-1pl.abs-obl+dyn-ждать] "мы вас ждём" и бжедугские формы sə-w-a-že [1sg.abs-2sg.io-obl+dyn-ждать] "я тебя жду", tə-ŝʷ-a-že [1sg.abs-2sg.io-obl+dyn-ждать] "мы вас ждём"; похожие формы [Ситимова 2004: 101]; [Ситимова 2004: 100-101] бжедугскае формы презенса qa-ḳʷe [dir+dyn-идти] "идёт сюда" и темиргоевская qe-ḳʷe [dir+dyn-идти] и другие.

### Values
There are the following value for each idiom:

* Temirgoi (Dzhambechi) -e- DYN —> ø / e_ [Тхаркахо 1993: 81] (про "огласовку в личных префиксах", на примере глагола 'ждать')
* Bzhedug  -e- DYN —> ø / e_ [Ситимова 2004: 96, 100-101] (из источника только примеры, но не интерпретация)
* Temirgoi  e —> ø / _e [Ситимова 2004: 96, 100-101] (из источника только примеры, но не интерпретация)
* Bzhedug  -e- DYN —> ø / e_ [Тхаркахо 1993: 71, 75] (Речь идёт о различном фонемном составе превербов на стр 71 и о директиве на стр 75.)
* Temirgoi  e —> ø / _e [Тхаркахо 1993: 71, 75] (Речь идёт о различном фонемном составе превербов на стр 71 и о директиве на стр 75.)
* Bzhedug  -e- DYN —> ø / e_ [Тхаркахо 1993: 81] (про "огласовку в личных префиксах", на примере глагола 'ждать')
* Temirgoi  e —> ø / _e [Тхаркахо 1993: 81] (про "огласовку в личных префиксах", на примере глагола 'ждать')

