## 18. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/18.html'>POT</a>
### Description

NA

конверб будущего времени
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
в шапсугском как бы по фонетическим причинам, но синхронно или диахронически?
в шапсугском как бы по фонетическим причинам, но синхронно или диахронически?
возможно, это более общее чередование. Про шапсугский написано странно: непонятно, и- только после директива или вообще после префиксов
возможно, это более общее чередование. Про шапсугский написано странно: непонятно, и- только после директива или вообще после префиксов
возможно, это более общее чередование. Про шапсугский написано странно: непонятно, и- только после директива или вообще после префиксов
NA
NA
NA
NA
NA
NA
NA
NA
NA
более присуще женщинам
NA
Содержат упоминание бога.
NA
NA
Джамбечийцы используют -рэ чаще других темиргоевцев.
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
суффиксы прошедших времен могут присоединяться к деепричастиям ("н.вр. - нсв, пр.вр. - св"). примеры только про имперфект, но может речь и про past тоже.
суффиксы прошедших времен могут присоединяться к деепричастиям ("н.вр. - нсв, пр.вр. - св"). примеры только про имперфект, но может речь и про past тоже.
NA
Я пока что не смог понять, как это соотносится с известными чередованиями.
Я пока что не смог понять, как это соотносится с известными чередованиями.
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
в примерах на адыгейский во множ числе только неотторжимые; если есть прилагательное, то на нем в ед числе может висеть падеж (70)
в примерах на адыгейский во множ числе только неотторжимые; если есть прилагательное, то на нем в ед числе может висеть падеж (70)
вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапс и бжед получается у глагола "делать" потенциалис кабардинский; интересный вопрос — что значит глагол шIэн с потенциалисом -ф (у Керашевой написано что-то невнятное)
вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапс и бжед получается у глагола "делать" потенциалис кабардинский; интересный вопрос — что значит глагол шIэн с потенциалисом -ф (у Керашевой написано что-то невнятное)
вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапс и бжед получается у глагола "делать" потенциалис кабардинский; интересный вопрос — что значит глагол шIэн с потенциалисом -ф (у Керашевой написано что-то невнятное)
вроде бы это фонетическая разница между адыгейским и кабардинским, но в шапс и бжед получается у глагола "делать" потенциалис кабардинский; интересный вопрос — что значит глагол шIэн с потенциалисом -ф (у Керашевой написано что-то невнятное)
NA
NA
тут похоже просто орфографическое различие
тут похоже просто орфографическое различие
еще Керашева пишет, что в шапсугском есть случаи лексикализации рефлексива и в таких глаголах он может появиться дважды (войти, помешивать) - вряд ли нам это нужно?
еще Керашева пишет, что в шапсугском есть случаи лексикализации рефлексива и в таких глаголах он может появиться дважды (войти, помешивать) - вряд ли нам это нужно?
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Не уточняется про лицо ИГ: "Имя, оформленное -мгьэ как будто выступает в роли субъекта". Речь идет о различии в функции инструменталиса с показателем эргатива (-м-гьэ) и без него (-гьэ).
NA
На примере 1sg
На примере 1sg
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Под корневым -ə- имеется в виду, что если глагол имеет в корне -e-, то он переходит в -ə-.
NA
NA
NA
NA
NA
NA
NA
NA
NA
Юра говорит, что у бжедугов это был суффикс
NA
NA
NA
NA
NA
NA
NA
NA
NA
При этом в вариантах словоформ, где /r/ не выпадает взят в скобки согласный /r/ абсолютива: txere(r) / txeer "пишущий"
NA
NA
Судя по примерам, в шапсугском в некоторых случаях тоже может выпадать.
NA
NA
NA
NA
NA
NA
Непонятно, из чего состоит показатели с гласной а вместо ы после т
Непонятно, из чего состоит показатели с гласной а вместо ы после т
NA
Непонятно, из чего состоит показатели с гласной а вместо ы после т
NA
NA
NA
NA
NA
NA
NA
NA
В [Ситимова 2004:81] написано "<...> восточных диалектов и адыгейского литературного языка"
(какой части речи форма на -гъу?) ; написано, что такого нет не только в тем., но и в других; Ю: это не причастие, а единый суффикс reʁʷe
(какой части речи форма на -гъу?) ; написано, что такого нет не только в тем., но и в других; Ю: это не причастие, а единый суффикс reʁʷe
NA
NA
NA
NA
NA
NA
В [Тхаркахо 1993: 83] сказано только про темиргоевское -λ и бжедугское -ŝ — что они добавляют значение "а ну!"
NA
NA
Cказано только про темиргоевское -λ и бжедугское -ŝ — что они добавляют значение "а ну!"
Cказано только про темиргоевское -λ и бжедугское -ŝ — что они добавляют значение "а ну!"
NA
NA
1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива: в единственном числе в темиргоевском и в обоих числах в бжедугском.
 2) Употребляется самостоятельно, судя по примеру
1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива: в единственном числе в темиргоевском и в обоих числах в бжедугском.
 2) Употребляется самостоятельно, судя по примеру
1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива, по крайней мере в единственном числе.
 2) Употребляется несамостоятельно, судя по примеру
1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива, по крайней мере в единственном числе.
 2) Употребляется несамостоятельно, судя по примеру
В бжедугском диалекте почти не встречается.
NA
В [Ситимова 2004: 82] имплицируется, что в литературном адыгейском это местоимение не имеет формы множественного числа
Форма зэкIэйи в источнике названа формой множественного числа и анализируется как форма зэкIэ-р-и, претерпевшая фонетические изменения, из чего, однако, следует, что она не содержит показатель плюралиса. См. [Nikolaeva 2012: 47] о форме zeč̣’e-r-jə [all-abs-&] как о "плавающем" (floating) аналоге zeč̣’e.
Имеет форму множественного числа zewəž'əxer.
NA
NA
В [Ситимова 2004:81] написано "<...> восточных диалектов и адыгейского литературного языка"
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Написано, что склоняется так же, как другие, но значение не описано
Основа ž’ə- может выступать без суффиксов. К основе ž’ə- может присоединяться -r, к которому может присоединяться показатель эргатива (ž’ə-r-me) и показатель плюралиса, к которому присоединяется показатель абсолютива или эргатива (ž’ə-r-xe-r, ž’ə-r-xe-m). С основой jež’ приведены только две формы: единственного числа jež’ər и множественного jež’ərxer, однако про формы эргатива не уточняется.
Плюралис и падежные показатели присоединяются непосредственно к основе jež'-.
В добавление к [Зэкох 1969: 87-88] отмечается, что в темиргоевском это местоимение может использоваться без показателей падежа (jež’). Примеры даны только с местоимением в абсолютивной роли. Кроме того, автору встретилась форма je, которая анализируется как усеченная форма местоимения jež’.
Местоимение имеет следующие формы (даны только формы единственного числа): jež’-ər абсолютив (в ист. патетив), jež’-əm эргатив, jež’-əm-č̣’e инструменталис (в ист. творительный), jež’-ər-ew авдербиалис (в ист. О[тносительный]), jež’-əm-djə адессив. Вместо предикативной формы используется конструкция с a-rə (jež’-ər a-rə zə-ʔʷa-ʁe-r "(Он) сам (есть) сказавший").
Местоимение имеет следующие формы (даны только формы единственного числа): jež’ абсолютив (в ист. патетив) или эргатив, jež’-ǯe / jež’-ər-ǯe инструменталис (в ист. творительный), jež’-ər-ew авдербиалис (в ист. О[тносительный]), jež’-djə адессив. Предикативная форма образуется прибавлением суффикса: jež’-ər.
NA
NA
NA
в абадз "неустойчивая диалектная форма"
в абадз "неустойчивая диалектная форма"
в абадз "неустойчивая диалектная форма"
в абадз "неустойчивая диалектная форма"
NA
NA
NA
NA
NA
NA
"Вместо аффикса -зэ выступают более сложные аффиксы, составной частью которых является и -зэ."
NA
"... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных"
"... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных"
"... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных"
"... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных"
NA
NA
NA
NA
NA
NA
NA
в аулах Тхагапш и Псеушхо в речи некоторых носителей иногда используется inalienable вместо alienable
в аулах Тхагапш и Псеушхо в речи некоторых носителей иногда используется inalienable вместо alienable
NA
Из примеров видно, что переводы очень условные
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
не только в повелительном наклонении, но и в "абсолютивах" - а может быть где-то еще?
не только в повелительном наклонении, но и в "абсолютивах" - а может быть где-то еще?
NA
NA
NA
NA
NA
NA
NA
Есть данные по ударению
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Два показателя совпадают по значению.
Два показателя совпадают по значению.
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Послелог и-блэкIь(эу) употребляется редко.
В нескольких примерах используется бенефактивный послелог.
NA
NA
NA
NA
NA
NA
NA
К послелогу присоединяются индексы со специальным аппликативом и суффикс инструменталиса
К послелогу присоединяются индексы со специальным аппликативом и суффикс инструменталиса
К послелогу присоединяются индексы со специальным аппликативом и суффикс инструменталиса
NA
NA
NA
Употребляется и в пространственном, и во временном значении
Употребляется и в пространственном, и во временном значении
NA
В [Ситимова 2004:81] написано "<...> восточных диалектов и адыгейского литературного языка"
NA
NA
непонятно, при каких именно условиях (примеров с и- не приводится)
непонятно, при каких именно условиях (примеров с и- не приводится)
NA
NA
NA
NA
NA
NA
NA
NA
На самом деле, в словоформах, приведены в пример, есть ещё преверб rə-: č̣’e-(λə-)rə-s "сидит возле кого-чего-л." и в следующем же абзаце написано про преверб č̣’e-λə-rə- (примеры с похожим значением).
На самом деле, в словоформах, приведены в пример, есть ещё преверб rə-: č̣’e-(λə-)rə-s "сидит возле кого-чего-л." и в следующем же абзаце написано про преверб č̣’e-λə-rə- (примеры с похожим значением).
На самом деле, в словоформах, приведены в пример, есть ещё преверб rə-: č̣’e-(λə-)rə-s "сидит возле кого-чего-л." и в следующем же абзаце написано про преверб č̣’e-λə-rə- (примеры с похожим значением).
NA
NA
NA
NA
Написано, что в шапсугском, как и в бжедугском, может использоваться и "нулевая морфема", но не приведено примеров.
NA
NA
NA
NA
NA
NA
NA
NA
NA
В примере префикс выглядит как р-, однако имплицируется, что в этом ауле представлен темиргоевский вариант ("В диалекте встречается и преверб зэр- в той же позиции")
NA
NA
NA
NA
предположительно, значение типа APUD
предположительно, значение типа APUD
предположительно, значение типа ALL
предположительно, значение типа ALL
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Вторая клауза оформлена эмфатическим -ba.
Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).
Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).
Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).
Не понятно про темиргоевский, при каких именно условиях используется -aa вместо -ʁe. В темиргоевских примерах на сочетание -FUT-PST-PST первый показатель претерита записан одной буквой a только в вариантах форм с показателем футурума -š't, но не -t (но в некоторых примерах с -t показатель претерита тоже -a, а не -aa).
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Если восточные диалекты у Ситимовой включают темиргоевский, написано, кажется, нечто странное
NA
NA
NA
NA
Ставится после прилагательного
NA
NA
В [Ситимова 2004:81] написано "<...> восточных диалектов и адыгейского литературного языка"
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
Сразу после идут примеры, которые этому не соответствуют!
Сразу после идут примеры, которые этому не соответствуют!
Сразу после идут примеры, которые этому не соответствуют!
NA
NA
из источника только примеры, но не интерпретация
из источника только примеры, но не интерпретация
Речь идёт о различном фонемном составе превербов на стр 71 и о директиве на стр 75.
Речь идёт о различном фонемном составе превербов на стр 71 и о директиве на стр 75.

### Values
There are the following value for each idiom:

* Bzhedug -шъу (но -ф с глаголом шIэн "делать") [Керашева 1957: 267]
* Kabardian -ф [Керашева 1957: 267]
* Shapsug -шъу (но -ф с глаголом шIэн "делать") [Керашева 1957: 267]
* SWC -шъу [Керашева 1957: 267]

