## 19. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/19.html' target='_blank'>выражение имперфекта</a>
tense; imperfect; auxiliary; morphology; phonology

### Description

Имперфект выражается присоединением вспомогательной основой с показателем прошедшего времени. Вспомогательная основа может выглядеть как š'tə- или tə- в разных диалектах. В значениях изоглосс записана основа с показателем прошедшего времени.

### Values
There are the following value for each idiom:

* Temirgoi (Dzherokaj) -š'təʁe, -š'taʁe, -taʁe [Ситимова 2004: 93] (Непонятно, из чего состоит показатели с гласной а вместо ы после т)
* Temirgoi (Khachemzij) -š'təʁe, -š'taʁe, -taʁe [Ситимова 2004: 93] (Непонятно, из чего состоит показатели с гласной а вместо ы после т)
* SWC  -š'təʁe [Кумахова 1972: 79-80] 
* Abzakh  -š'təʁe, -təʁe [Кумахова 1972: 79-80] 
* Abzakh  -təʁe [Ситимова 2004: 93] 
* Bzhedug  -təʁe [Ситимова 2004: 93] 
* Shapsug  -štəʁe [Ситимова 2004: 93] 
* SWC  -š'təʁe [Ситимова 2004: 93] 
* Temirgoi  -š'təʁe, -š'taʁe [Ситимова 2004: 93] (Непонятно, из чего состоит показатели с гласной а вместо ы после т)

