## 50. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/50.html'>движение "изнутри"</a>
### Description

Источник движения, по-видимому, может выражаться превербом jə-. По [Тхаркахо 1993: 75-76] движение "изнутри" (например, из корзины) выражается превербом къи-/къе- (что трактуется нами как сочетание директива и преверба), при этом движение "оттуда сюда" (например, из аула) в темиргоевском выражается так же, а в бжедугском выражается превербом къэ- (в нашей терминологии, директив). Преверб къе- появляется в обоих диалектах в формах настоящего времени, то есть, видимо, перед префиксом динамичности. Однако, Тхаркахо обращает внимание на то, что в темиргоевском преверб выглядет как къе- даже перед личными префиксами (что неожиданно, так как в этом случае за ним уже не следует префикс динамичности), в отличие от литературного, где в таком случае используется -къи.


### Values
There are the following value for each idiom:

* Bzhedug qe- [DIR-] "оттуда сюда" vs. q-jə- [DIR-LOC-] "изнутри" [Тхаркахо 1993: 75-76]
* Temirgoi q-jə- [DIR-LOC-] "оттуда сюда" и "изнутри" [Тхаркахо 1993: 75-76]

