## 65. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/65.html'>конверб на -zə</a>
converb; morphology

### Description

Показатель инфинитности -zə есть только в абадзехском.

### Values
There are the following value for each idiom:

* Abzakh  да [Кумахова 1972: 76-77] (конверб будущего времени)
* Abzakh  да [Ситимова 2004: 85-86] (При перечислении последовательно произошедших в прошлом событий, глагол, обозначающий первое из них, оформляется разными суффиксами.)
* Abzakh  да [Тхаркахо 1993: 84] (При перечислении последовательно произошедших в прошлом событий, глагол, обозначающий первое из них, оформляется разными суффиксами.)
* Abzakh  да [Керашева 1957: 270] 
* Bzhedug  нет [Керашева 1957: 270] ("... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных")
* Shapsug  нет [Керашева 1957: 270] ("... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных")
* SWC  нет [Керашева 1957: 270] ("... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных")
* Temirgoi  нет [Керашева 1957: 270] ("... -зы является характерным только для абадзехского диалекта и не наблюдается в остальных")

