## 70. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/70.html'>конверб на аддитив -jə</a>
coordination

### Description



### Values
There are the following value for each idiom:

* Abzakh  да [Кумахова 1972: 76-77] 
* Abzakh  да [Ситимова 2004: 85-86] (При перечислении последовательно произошедших в прошлом событий, глагол, обозначающий первое из них, оформляется разными суффиксами.)
* Bzhedug  да [Ситимова 2004: 85-86] (При перечислении последовательно произошедших в прошлом событий, глагол, обозначающий первое из них, оформляется разными суффиксами.)
* Shapsug  да [Керашева 1957: 271-272] 
* Shapsug  да [Ситимова 2004: 85-86] (При перечислении последовательно произошедших в прошлом событий, глагол, обозначающий первое из них, оформляется разными суффиксами.)
* SWC  да [Кумахова 1972: 76] 
* Abzakh  да [Ситимова 2004: 87] (сочинение императивов)
* Bzhedug  да [Ситимова 2004: 87] (сочинение императивов)
* Shapsug  да [Ситимова 2004: 87] (сочинение императивов)
* Temirgoi  да [Ситимова 2004: 87] (сочинение императивов)
* Temirgoi  да [Тхаркахо 1993: 83] (сочинение императивов)

