## 88. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/88.html'>местоимение-интенсификатор</a>
### Description

Встречаются различные варианты местоимения-интенсификатора, которые отличаются 1) тем, присоединяют ли они показатели числа и падежа, и присутствует ли перед этими показателями -r- (встречающийся и в других местоимениях); 2) своей основой (не считая -r-). В значении изоглоссы дана основа, а в комментарии находятся данные в источнике сведения о присоединении к основам показателей числа и падежа.

### Values
There are the following value for each idiom:

* Shapsug  jež’, ž’ə [Керашева 1957: 254] (Основа ž’ə- может выступать без суффиксов. К основе ž’ə- может присоединяться -r, к которому может присоединяться показатель эргатива (ž’ə-r-me) и показатель плюралиса, к которому присоединяется показатель абсолютива или эргатива (ž’ə-r-xe-r, ž’ə-r-xe-m). С основой jež’ приведены только две формы: единственного числа jež’ər и множественного jež’ərxer, однако про формы эргатива не уточняется.)
* Temirgoi  jež’ [Керашева 1957: 254] (Плюралис и падежные показатели присоединяются непосредственно к основе jež'-.)
* Temirgoi  jež’, редко je [Тхаркахо 1993: 94] (В добавление к [Зэкох 1969: 87-88] отмечается, что в темиргоевском это местоимение может использоваться без показателей падежа (jež’). Примеры даны только с местоимением в абсолютивной роли. Кроме того, автору встретилась форма je, которая анализируется как усеченная форма местоимения jež’.)
* Temirgoi  jež’ [Зэкох 1969: 87-88] (Местоимение имеет следующие формы (даны только формы единственного числа): jež’-ər абсолютив (в ист. патетив), jež’-əm эргатив, jež’-əm-č̣’e инструменталис (в ист. творительный), jež’-ər-ew авдербиалис (в ист. О[тносительный]), jež’-əm-djə адессив. Вместо предикативной формы используется конструкция с a-rə (jež’-ər a-rə zə-ʔʷa-ʁe-r "(Он) сам (есть) сказавший").)
* Bzhedug  jež’ [Зэкох 1969: 87-88] (Местоимение имеет следующие формы (даны только формы единственного числа): jež’ абсолютив (в ист. патетив) или эргатив, jež’-ǯe / jež’-ər-ǯe инструменталис (в ист. творительный), jež’-ər-ew авдербиалис (в ист. О[тносительный]), jež’-djə адессив. Предикативная форма образуется прибавлением суффикса: jež’-ər.)
* Bzhedug  jež’ [Ситимова 2004: 80] (Местоимение имеет следующие формы. В единственном числе: jež’ абсолютив (в ист. именительный) или эргатив, jež’-ǯe / jež’-ər-ǯe инструменталис (в ист. орудный), jež’-ər-ew авдербиалис (в ист. превратительный). Во множественном числе (в том же порядке): jež’-xe(-r), jež’-me, jež’-xe-m-ǯe, jež’-x-ew)
* Temirgoi  jež’ [Ситимова 2004: 80] (Местоимение имеет следующие формы. В единственном числе: jež’ə(-r) абсолютив (в ист. именительный), jež’ə(-m) эргатив, jež’ə(-m)-č̣’e инструменталис (в ист. орудный), jež’-ər-ew авдербиалис (в ист. превратительный). Во множественном числе (в том же порядке): jež’-xe-r, jež’-xe-m, jež’-xe-m-č̣’e, jež’-x-ew)

