## 94. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/94.html'>неотторжимая принадлежность</a>
possession

### Description

В конструкции отторжимой принадлежности между основой вершинного имени и префиксом посессора появляется посессивный префикс, а в конструкции неотторжимой принадлежности индекс посессора присоединяется непосредственно к основе вершинного имени. В изоглоссе отмечено наличие имён, использующих конструкцию неотторжимой принадлежности (будучи обладаемым).

### Values
There are the following value for each idiom:

* Kabardian (Pseushkho) да [Керашева 1957: 253] (Иногда используется неотторжимая вместо отторжимой)
* Shapsug (Tkhagapsh) да [Керашева 1957: 253] (Иногда используется неотторжимая вместо отторжимой)
* Besleney  да [Керашева 1957: 253] (Очень маленький класс имён.)
* Shapsug  да [Керашева 1957: 253] 
* Kabardian  нет [Кумахов 2013: 73-74] 
* Kabardian  нет [Кумахова 1972: 69-71] 
* Abzakh  да [Кумахова 1972: 69-71] (Возможно использование отторжимой вместо неотторжимой.)
* Kuban  нет [Кумахова 1972: 69-71] 
* SWC  да [Рогава, Керашева 1966: 68] 

