## 96. <a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/96.html'>неопределенное местоимение</a>
### Description

Слово, переводимое на русский с помощью слова какой-то

### Values
There are the following value for each idiom:

* Bzhedug  zəgawe [Ситимова 2004: 82-83] (1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива: в единственном числе в темиргоевском и в обоих числах в бжедугском.
2) Употребляется самостоятельно, судя по примеру)
* Temirgoi  zəgawre [Ситимова 2004: 82-83] (1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива: в единственном числе в темиргоевском и в обоих числах в бжедугском.
2) Употребляется самостоятельно, судя по примеру)
* Bzhedug  gaw(r)e [Ситимова 2004: 84] (1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива, по крайней мере в единственном числе.
2) Употребляется несамостоятельно, судя по примеру)
* Temirgoi  gawre [Ситимова 2004: 84] (1) Склоняется по падежам и числам, но не присоединяет показатель абсолютива, по крайней мере в единственном числе.
2) Употребляется несамостоятельно, судя по примеру)

