---
output: 
  html_document:
    css: /home/agricolamz/work/databases/The_Circassian_Isoglosses_Database/my.css
---

```{r, include=FALSE}
library(DT)
library(tidyverse)
knitr::opts_chunk$set(echo=FALSE, message=FALSE)
```


### {.tabset .tabset-fade .tabset-pills}
#### Partial data
```{r}
# change titles to links
read_tsv("https://raw.githubusercontent.com/agricolamz/The_Circassian_Isoglosses_Database/master/database.csv") %>% 
  mutate(id = as.integer(factor(title)),
    title = paste0("<a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/",
                   id,
                   ".html'>",
                    title,
                   "</a>")) ->
  db

db %>% 
  mutate(value = paste(value, "<br>", source)) %>%
  group_by(id) %>% 
  mutate(impact = n()) %>%
  group_by(id, idiom) %>% 
  mutate(value = str_c(value, collapse = "<br>")) %>% 
  select(impact, title, topic, contributor, idiom, value) %>% 
  distinct() %>% 
  spread(idiom, value) %>% 
  mutate_all(function(x){ifelse(is.na(x), "", x)}) %>% 
  datatable(escape = FALSE, rownames = FALSE,
            extensions = c('ColReorder', 'Buttons'),
            filter = list(position = 'top', clear = TRUE),
            options = list(pageLength = 20, 
                           dom = 'Btip', 
                           autoWidth = TRUE, 
                           colReorder = TRUE, 
                           buttons = I('colvis')))
```

#### Whole dataset
```{r}
DT::datatable(db[,-6],escape = FALSE, rownames = FALSE,
              extensions = c('ColReorder', 'Buttons'),
              filter = list(position = 'top', clear = TRUE),
              options = list(pageLength = 20, dom = 'Btip', autoWidth = TRUE, colReorder = TRUE, buttons = I('colvis'))) # remove description column
```


```{r, include=FALSE}
# isoglosses creation

sapply(seq_along(db$id), function(i){
  indexes <- which(db$id %in% db$id[i])
  title <- paste0("## ", db$id[i], ". ", db$title[i])
  description <- c(db$key_words[i],"",  "### Description", "", 
                   ifelse(is.na(db$description[i]), "", db$description[i]),
                   "")
  
  db$comment[!is.na(db$comment)] <- paste0("(", db$comment[!is.na(db$comment)], ")")
  db$comment[is.na(db$comment)] <- ""
    db$village[!is.na(db$village)] <- paste0("(", db$village[!is.na(db$village)], ")")
  db$village[is.na(db$village)] <- ""
  
  
  values <- c("### Values",
              "There are the following value for each idiom:",
              "",
              paste("*", 
                    db$idiom[indexes],
                    db$village[indexes],
                    db$value[indexes], 
                    db$source[indexes],
                    db$comment[indexes]), 
              "")
  text <- c(title, description, values)
  writeLines(text, paste0(db$id[i], ".Rmd"))
  }
)
```

```{r, include=FALSE, eval=FALSE}
# создает график
library(tidyverse)
read_tsv("https://raw.githubusercontent.com/agricolamz/The_Circassian_Isoglosses_Database/master/database.csv") %>% 
  group_by(title) %>% 
  mutate(impact =  n()) %>%
  ungroup() %>% 
  count(impact) %>% 
  ggplot(aes(impact, n))+
  geom_line()+
  geom_point(size = 3)+
  scale_x_continuous(breaks = 0:12)+
  theme_bw()+
  labs(x = "number of rows per isogloss",
       y = "number of isoglosses")
```

