<style> div.main-container { max-width: 1600px; } </style>

```{r sets table 1, include=FALSE}
library(DT)
library(tidyverse)
knitr::opts_chunk$set(echo=FALSE, message=FALSE)
```

```{r render table 1}
read_tsv("https://raw.githubusercontent.com/agricolamz/The_Circassian_Isoglosses_Database/master/database.csv") %>% 
  mutate(id = as.integer(factor(title)),
         title = paste0("<a href =  'https://agricolamz.github.io/The_Circassian_Isoglosses_Database/",
                        id,
                        ".html' target='_blank'>",
                        title,
                        "</a>")) ->
  db

db %>% 
  mutate(value = paste(value, "<br>", source)) %>%
  group_by(id) %>% 
  mutate(impact = n()) %>%
  group_by(id, idiom) %>% 
  mutate(value = str_c(value, collapse = "<br>")) %>% 
  select(impact, title, topic, contributor, idiom, value) %>% 
  distinct() %>% 
  spread(idiom, value) %>% 
  mutate_all(function(x){ifelse(is.na(x), "", x)}) %>% 
  datatable(escape = FALSE, rownames = FALSE,
            extensions = c('ColReorder', 'Buttons', 'FixedHeader'),
            filter = list(position = 'top', clear = TRUE),
            options = list(
              dom = 'Btip', 
              autoWidth = TRUE, 
              colReorder = TRUE, 
              buttons = I('colvis'),
              fixedHeader = TRUE,
              pageLength = 20))
```